"""empty message

Revision ID: 87c8f3102e1a
Revises: 
Create Date: 2025-05-26 16:26:19.571411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c8f3102e1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_edited_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_edited_by_id'], ['user.id'], name='fk_post_last_edited_by_user'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_post_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('editor_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('diff', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['editor_id'], ['user.id'], name='fk_edit_history_editor_id'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='fk_edit_history_post_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edit_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edit_history_editor_id'), ['editor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edit_history_post_id'), ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edit_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edit_history_post_id'))
        batch_op.drop_index(batch_op.f('ix_edit_history_editor_id'))

    op.drop_table('edit_history')
    op.drop_table('post')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))

    op.drop_table('user')
    # ### end Alembic commands ###
